services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: smart-voice-db
    restart: always
    environment:
      POSTGRES_USER: maike_user
      POSTGRES_PASSWORD: maike_password
      POSTGRES_DB: smart_voice_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Interface Web para gerenciar o banco (Adminer)
  adminer:
    image: adminer
    container_name: smart-voice-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
