spring.application.name=smart-voice-api-spring-boot

# Configurações do Banco (PostgreSQL Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_voice_api
spring.datasource.username=maike_user
spring.datasource.password=maike_password
spring.jpa.hibernate.ddl-auto=update

# Configurações Spring AI (Use variáveis de ambiente por segurança!)
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.servlet.multipart.max-file-size=10MB
